Replace old code with new version t init Reinitialized existing Git repository in C:/Users/DimitriousGeorgiou/eclipse-workspace/UNQUIZ/.git/
AzureAD+DimitriousGeorgiou@D-WA14-109-09 MINGW64
~/eclipse-workspace/UNQUIZ (main)
$ git add .

AzureAD+DimitriousGeorgiou@D-WA14-109-09 MINGW64
~/eclipse-workspace/UNQUIZ (main)
$ git commit -m "Replace old code with new version"
[main 06c8800] Replace old code with new version
 60 files changed, 12698 insertions(+), 11102 deletions(-)
  delete mode 100644 DatenbankStruc.txt
   delete mode 100644 ProjektDocumentation
    delete mode 100644 SECURITY.md
     create mode 100644 sorting_config.dat

     AzureAD+DimitriousGeorgiou@D-WA14-109-09 MINGW64
     ~/eclipse-workspace/UNQUIZ (main)
     $ git push origin main
     To github.com:GDayIT/UNQUIZ.git
     error: failed to push some refs to 'github.com:GDayIT/UNQUIZ.git'
     hint: Updates were rejected because the remote contains work that
     you do not
     hint: have locally. This is usually caused by another repository
     pushing to
     hint: the same ref. If you want to integrate the remote changes,
     use
     hint: 'git pull' before pushing again.
     hint: See the 'Note about fast-forwards' in 'git push --help' for
     details.

     AzureAD+DimitriousGeorgiou@D-WA14-109-09 MINGW64
     ~/eclipse-workspace/UNQUIZ (main)
     $ git fetch origin
     remote: Enumerating objects: 5, done.
     remote: Counting objects: 100% (5/5), done.
     remote: Compressing objects: 100% (3/3), done.
     remote: Total 3 (delta 2), reused 0 (delta 0), pack-reused 0 (from
     0)
     Unpacking objects: 100% (3/3), 1.16 KiB | 69.00 KiB/s, done.
     From github.com:GDayIT/UNQUIZ
        196329a..997f215  main       -> origin/main

	$ git push origin main
	To github.com:GDayIT/UNQUIZ.git
	 ! [rejected]        main -> main (non-fast-forward)
	 error: failed to push some refs to
	 'github.com:GDayIT/UNQUIZ.git'
	 hint: Updates were rejected because the tip of your current
	 branch is behind
	 hint: its remote counterpart. If you want to integrate the
	 remote changes,
	 hint: use 'git pull' before pushing again.

t init
Reinitialized existing Git repository in
C:/Users/DimitriousGeorgiou/eclipse-workspace/UNQUIZ/.git/

AzureAD+DimitriousGeorgiou@D-WA14-109-09 MINGW64
~/eclipse-workspace/UNQUIZ (main)
$ git add .

AzureAD+DimitriousGeorgiou@D-WA14-109-09 MINGW64
~/eclipse-workspace/UNQUIZ (main)
$ git commit -m "Replace old code with new version"
[main 06c8800] Replace old code with new version
 60 files changed, 12698 insertions(+), 11102 deletions(-)
  delete mode 100644 DatenbankStruc.txt
   delete mode 100644 ProjektDocumentation
    delete mode 100644 SECURITY.md
     create mode 100644 sorting_config.dat

     AzureAD+DimitriousGeorgiou@D-WA14-109-09 MINGW64
     ~/eclipse-workspace/UNQUIZ (main)
     $ git push origin main
     To github.com:GDayIT/UNQUIZ.git
     error: failed to push some refs to 'github.com:GDayIT/UNQUIZ.git'
     hint: Updates were rejected because the remote contains work that
     you do not
     hint: have locally. This is usually caused by another repository
     pushing to
     hint: the same ref. If you want to integrate the remote changes,
     use
     hint: 'git pull' before pushing again.
     hint: See the 'Note about fast-forwards' in 'git push --help' for
     details.

     AzureAD+DimitriousGeorgiou@D-WA14-109-09 MINGW64
     ~/eclipse-workspace/UNQUIZ (main)
     $ git fetch origin
     remote: Enumerating objects: 5, done.
     remote: Counting objects: 100% (5/5), done.
     remote: Compressing objects: 100% (3/3), done.
     remote: Total 3 (delta 2), reused 0 (delta 0), pack-reused 0 (from
     0)
     Unpacking objects: 100% (3/3), 1.16 KiB | 69.00 KiB/s, done.
     From github.com:GDayIT/UNQUIZ
        196329a..997f215  main       -> origin/main

	$ git push origin main
	To github.com:GDayIT/UNQUIZ.git
	 ! [rejected]        main -> main (non-fast-forward)
	 error: failed to push some refs to
	 'github.com:GDayIT/UNQUIZ.git'
	 hint: Updates were rejected because the tip of your current
	 branch is behind
	 hint: its remote counterpart. If you want to integrate the
	 remote changes,
	 hint: use 'git pull' before pushing again.
t init
Reinitialized existing Git repository in
C:/Users/DimitriousGeorgiou/eclipse-workspace/UNQUIZ/.git/

AzureAD+DimitriousGeorgiou@D-WA14-109-09 MINGW64
~/eclipse-workspace/UNQUIZ (main)
$ git add .

AzureAD+DimitriousGeorgiou@D-WA14-109-09 MINGW64
~/eclipse-workspace/UNQUIZ (main)
$ git commit -m "Replace old code with new version"
[main 06c8800] Replace old code with new version
 60 files changed, 12698 insertions(+), 11102 deletions(-)
  delete mode 100644 DatenbankStruc.txt
   delete mode 100644 ProjektDocumentation
    delete mode 100644 SECURITY.md
     create mode 100644 sorting_config.dat

     AzureAD+DimitriousGeorgiou@D-WA14-109-09 MINGW64
     ~/eclipse-workspace/UNQUIZ (main)
     $ git push origin main
     To github.com:GDayIT/UNQUIZ.git
     error: failed to push some refs to 'github.com:GDayIT/UNQUIZ.git'
     hint: Updates were rejected because the remote contains work that
     you do not
     hint: have locally. This is usually caused by another repository
     pushing to
     hint: the same ref. If you want to integrate the remote changes,
     use
     hint: 'git pull' before pushing again.
     hint: See the 'Note about fast-forwards' in 'git push --help' for
     details.

     AzureAD+DimitriousGeorgiou@D-WA14-109-09 MINGW64
     ~/eclipse-workspace/UNQUIZ (main)
     $ git fetch origin
     remote: Enumerating objects: 5, done.
     remote: Counting objects: 100% (5/5), done.
     remote: Compressing objects: 100% (3/3), done.
     remote: Total 3 (delta 2), reused 0 (delta 0), pack-reused 0 (from
     0)
     Unpacking objects: 100% (3/3), 1.16 KiB | 69.00 KiB/s, done.
     From github.com:GDayIT/UNQUIZ
        196329a..997f215  main       -> origin/main

	$ git push origin main
	To github.com:GDayIT/UNQUIZ.git
	 ! [rejected]        main -> main (non-fast-forward)
	 error: failed to push some refs to
	 'github.com:GDayIT/UNQUIZ.git'
	 hint: Updates were rejected because the tip of your current
	 branch is behind
	 hint: its remote counterpart. If you want to integrate the
	 remote changes,
	 hint: use 'git pull' before pushing again.
	 t init
	 Reinitialized existing Git repository in
	 C:/Users/DimitriousGeorgiou/eclipse-workspace/UNQUIZ/.git/

	 AzureAD+DimitriousGeorgiou@D-WA14-109-09 MINGW64
	 ~/eclipse-workspace/UNQUIZ (main)
	 $ git add .

	 AzureAD+DimitriousGeorgiou@D-WA14-109-09 MINGW64
	 ~/eclipse-workspace/UNQUIZ (main)
	 $ git commit -m "Replace old code with new version"
	 [main 06c8800] Replace old code with new version
	  60 files changed, 12698 insertions(+), 11102 deletions(-)
	   delete mode 100644 DatenbankStruc.txt
	    delete mode 100644 ProjektDocumentation
	     delete mode 100644 SECURITY.md
	      create mode 100644 sorting_config.dat

	      AzureAD+DimitriousGeorgiou@D-WA14-109-09 MINGW64
	      ~/eclipse-workspace/UNQUIZ (main)
	      $ git push origin main
	      To github.com:GDayIT/UNQUIZ.git
	      error: failed to push some refs to
	      'github.com:GDayIT/UNQUIZ.git'
	      hint: Updates were rejected because the remote contains
	      work that you do not
	      hint: have locally. This is usually caused by another
	      repository pushing to
	      hint: the same ref. If you want to integrate the remote
	      changes, use
	      hint: 'git pull' before pushing again.
	      hint: See the 'Note about fast-forwards' in 'git push
	      --help' for details.

	      AzureAD+DimitriousGeorgiou@D-WA14-109-09 MINGW64
	      ~/eclipse-workspace/UNQUIZ (main)
	      $ git fetch origin
	      remote: Enumerating objects: 5, done.
	      remote: Counting objects: 100% (5/5), done.
	      remote: Compressing objects: 100% (3/3), done.
	      remote: Total 3 (delta 2), reused 0 (delta 0), pack-reused
	      0 (from 0)
	      Unpacking objects: 100% (3/3), 1.16 KiB | 69.00 KiB/s,
	      done.
	      From github.com:GDayIT/UNQUIZ
	         196329a..997f215  main       -> origin/main

		 $ git push origin main
		 To github.com:GDayIT/UNQUIZ.git
		  ! [rejected]        main -> main (non-fast-forward)
		  error: failed to push some refs to
		  'github.com:GDayIT/UNQUIZ.git'
		  hint: Updates were rejected because the tip of your
		  current branch is behind
		  hint: its remote counterpart. If you want to integrate
		  the remote changes,
		  hint: use 'git pull' before pushing again.
		  #